### PR TITLE
Feature/upgrade deps

### PR DESCRIPTION
**Pull request by BrunnerLivio**

### CODE REVIEW

**Comment by erickellerek1** [comment]
thanks for the update.

**Comment by BrunnerLivio** [comment]
@erickellerek1 
will fix test tomorrow!

**Comment by erickellerek1** [comment]
I did spawn a new instance so all dependencies works I will merge this PR then if you are ok with it...

**Comment by erickellerek1** [comment]
still we shall automate the process with the tool you mentioned `Renovate`

**Comment by BrunnerLivio** [comment]
Alright, sure! 
Maybe we need to use Greenkeeper #45 - I think Renovate is not free. But Greenkeeper is also cool :) Will set it up asap, so we do not have to bother about the deps so much!

**Pull request merged**
