### PR TITLE
[WIP] Add lxdhub web

### PR DESCRIPTION
**Pull request by BrunnerLivio**
This PR adds the source code of [lxdhub-web](https://github.com/Roche/lxdhub-web), enabling to release the complete LXDHub (including web frontend) in one go. 

The lxdhub-web repo can be removed after this PR.

### CODE REVIEW

**Comment by randombenj** [comment]
Will this be continued? This would be quite usefull :)

**Comment by BrunnerLivio** [comment]
@randombenj I think the only thing missing is the integration of the CI testing. Shouldn’t be too hard to update that :)

**Comment by randombenj** [comment]
Okay maybe I could also have a look at that if I have time :+1:

**Comment by randombenj** [comment]
@BrunnerLivio could you check wether this is ok? :smile:

**Comment by randombenj** [comment]
shipping

**Pull request merged**
